# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
    timezone: "America/Los_Angeles" # Pacific Time
  labels:
  - "category: engineering"
  - dependencies
  commit-message:
    prefix: chore
    include: scope
  versioning-strategy: increase
  ignore:
    # axe-core updates require extra validation and synchronization with
    # accessibility-insights-web; we handle them as features, not auto-updates.
  - dependency-name: axe-core
    versions:
    - ">= 0"
    # puppeteer-core is tightly coupled to our apify dependency via
    # accessibility-insights-service. We can't take updates to it until we
    # finish updating to apify v1.
  - dependency-name: puppeteer-core
    versions:
    - "> 5.3.1"
    # office-ui-fabric-react is bound to v16 of @types/react
  - dependency-name: "@types/react"
    versions:
    - ">= 17"
    # office-ui-fabric-react is bound to v16 of @types/react
  - dependency-name: "@types/react-dom"
    versions:
    - ">= 17"
    # Each of the below dependencies has dropped support for node v10 in their
    # latest versions, but we need to maintain node v10 support because that's
    # the latest we're allowed to depend on as a custom ADO task.
    #
    # marked-terminal v5 depends on chalk v5 which uses the node: protocol;
    # this protocol is not supported in node 10, the ADO execution environment
  - dependency-name: marked-terminal
    versions:
    - ">= 5"
    # get-port v6+ is pure ESM and requires node >= 12.20
  - dependency-name: get-port
    versions:
    - ">= 6"
    # serialize-error v9+ is pure ESM and requires node >= 12.20
  - dependency-name: serialize-error
    versions:
    - ">= 9"
