# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: 'Accessibility Insights Action'
description: 'Task to scan for accessibility issues'
inputs:
    output-dir:
        description: 'Folder containing the scan report.'
        default: '_accessibility-reports'
        required: true
    site-dir:
        description: 'Folder containing website content.'
        default: ${{ github.workspace }}
        required: true
    scan-url-relative-path:
        description: 'Relative path to directory used to construct base scan url. e.g. / on Ubuntu and // on Windows'
        required: true
        default: '/'
    chrome-path:
        description: 'Path to Chrome executable.'
        required: false
    repo-token:
        description: 'GitHub API access token.'
        required: true
    url:
        description: 'The hosted URL to scan/crawl for accessibility issues.'
        required: false
    max-urls:
        description: 'Maximum number of pages opened by crawler. The crawl will stop when this limit is reached.'
        required: false
        default: '100'
    discovery-patterns:
        description: 'List of RegEx patterns to crawl in addition to the provided URL, separated by space.'
        required: false
    input-file:
        description: 'File path that contains list of URLs (each separated by a new line) to scan in addition to URLs discovered from crawling the provided URL.'
        required: false
    input-urls:
        description: 'List of URLs to crawl in addition to URLs discovered from crawling the provided URL, separated by space.'
        required: false
    localhost-port:
        description: 'The preferred local website TCP port to use when scanning local website content.'
        required: false
    scan-timeout:
        description: 'The maximum timeout in milliseconds for the scan (excluding dependency setup)'
        required: false
        default: 90000
runs:
    using: 'node12'
    main: 'dist/index.js'
