# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: 'Accessibility Insights Action'
description: 'Task to scan for accessibility issues'
inputs:
    output-dir:
        description: 'folder containing the generated report'
        default: '_accessibility-reports'
        required: true
    site-dir:
        description: 'folder containing site content'
        default: ${{ github.workspace }}
        required: true
    scan-url-relative-path:
        description: 'relative path from url domain. Eg: /index.html'
        required: true
        default: '/'
    chrome-path:
        description: 'path to chrome executable'
        required: false
    repo-token:
        description: 'github token'
        required: true
    url:
        description: 'The hosted URL to scan/crawl for accessibility issues.'
        required: false
    max-urls:
        description: 'Maximum number of pages opened by crawler. The crawl will stop when this limit is reached.'
        required: false
        default: '100'
    discovery-patterns:
        description: 'List of URLs to crawl in addition to URLs discovered from crawling the provided URL, separated by space.'
        required: false
    input-file:
        description: 'File path that contains list of URLs (each separated by a new line) to scan in addition to URLs discovered from crawling the provided URL.'
        required: false
    input-urls:
        description: 'List of URLs to crawl in addition to URLs discovered from crawling the provided URL, separated by space.'
        required: false
runs:
    using: 'node12'
    main: 'dist/index.js'
