# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: 'Accessibility Insights Action'
description: 'Task to scan for accessibility issues'
inputs:
    output-dir:
        description: 'folder containing the generated report'
        default: '_accessibility-reports'
        required: true
    site-dir:
        description: 'folder containing site content'
        default: ${{ github.workspace }}
        required: true
    scan-url-relative-path:
        description: 'relative path from url domain. Eg: /index.html'
        required: true
        default: '/'
    chrome-path:
        description: 'path to chrome executable'
        required: false
    repo-token:
        description: 'github token'
        required: true
    url:
        description: 'remote site url'
        required: false
runs:
    using: 'node12'
    main: 'dist/index.js'
