# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

on: [push]

jobs:
    local_action_run:
        runs-on: ubuntu-latest
        name: Run action in a local dev environment
        steps:
            - name: Scan local website for accessibility issues
              uses: ./
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  site-dir: ${{ github.workspace }}/dev/website-root
                  localhost-port: 53800
