# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: 'Accessibility Insights Action'
description: 'Task to scan for accessibility issues'
inputs:
    output-dir:
        description: 'Folder containing the scan report.'
        default: '_accessibility-reports'
        required: true
    site-dir:
        description: 'Folder containing website content.'
        default: ${{ github.workspace }}
        required: true
    scan-url-relative-path:
        description: 'Relative path to directory used to construct base scan url. e.g. / on Ubuntu and // on Windows'
        required: true
        default: '/'
    chrome-path:
        description: 'Path to Chrome executable.'
        required: false
    repo-token:
        description: 'GitHub API access token.'
        required: true
    url:
        description: 'The hosted URL to scan/crawl for accessibility issues.'
        required: false
    max-urls:
        description: 'Maximum number of pages opened by crawler. The crawl will stop when this limit is reached.'
        required: false
        default: '100'
    discovery-patterns:
        description: 'List of RegEx patterns to crawl in addition to the provided URL, separated by space.'
        required: false
    input-file:
        description: 'File path that contains list of URLs (each separated by a new line) to scan in addition to URLs discovered from crawling the provided URL.'
        required: false
    input-urls:
        description: 'List of URLs to crawl in addition to URLs discovered from crawling the provided URL, separated by space.'
        required: false
    localhost-port:
        description: 'The preferred local website TCP port to use when scanning local website content.'
        required: false
    scan-timeout:
        description: 'The maximum timeout in milliseconds for the scan (excluding dependency setup)'
        required: false
        default: 90000
    base-line:
        description: 'Generate Baseline if true.'
        required: true
        default: true
    base-line-file:
        description: 'Path to existing baseline file, will generate delta between the generated one and the old one if exists.'
        required: true
        default: true
runs:
    using: 'composite'
    steps:
        - name: Install npm packages
          run: |
              echo 'Installing npm packages...'
              cd $GITHUB_ACTION_PATH/dist && yarn install --frozen-lockfile --production --ignore-optional --ignore-engines
              echo 'npm packages successfully installed'
          shell: bash
        - name: Setup local docker container
          run: |
              if [[ $ACT == true && ! -f '/usr/bin/chromium' ]]; then
                  apt-get update \
                  && apt-get -y install chromium chromium-l10n \
                  && apt-get -y install procps
                  echo 'Chromium package successfully installed on docker container'
              fi
          shell: bash
        - name: Run action
          run: |
              echo 'Starting accessibility scanner...'
              node $GITHUB_ACTION_PATH/dist/index.js
          shell: bash
          env:
              INPUT_OUTPUT-DIR: ${{ inputs.output-dir }}
              INPUT_SITE-DIR: ${{ inputs.site-dir }}
              INPUT_SCAN-URL-RELATIVE-PATH: ${{ inputs.scan-url-relative-path }}
              INPUT_CHROME-PATH: ${{ inputs.chrome-path }}
              INPUT_REPO-TOKEN: ${{ inputs.repo-token }}
              INPUT_URL: ${{ inputs.url }}
              INPUT_MAX-URLS: ${{ inputs.max-urls }}
              INPUT_DISCOVERY-PATTERNS: ${{ inputs.discovery-patterns }}
              INPUT_INPUT-FILE: ${{ inputs.input-file }}
              INPUT_INPUT-URLS: ${{ inputs.input-urls }}
              INPUT_LOCALHOST-PORT: ${{ inputs.localhost-port }}
              INPUT_SCAN-TIMEOUT: ${{ inputs.scan-timeout }}
