# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# This pipeline covers the staging scenarios for the ADO extension as triggered for
# a PR/CI build of a GitHub repo. Note that release validation *also* requires covering
# PR/CI scenarios as triggered from an ADO repo; see the release validation OneNote
# template for details.

# A CI build will be automatically kicked off when the "publish to production" stage
# of prod-release is run. A PR build which triggers this pipeline can be run be
# creating a PR which touches any file under the "/dev" folder.

trigger: none

pr:
    branches:
        include:
            - main
    paths:
        include:
            - dev
            - pipelines/ado-extension-prod-validation.yaml
            - pipelines/ado-extension-validation-template.yaml

resources:
    pipelines:
        - pipeline: prod-release
          source: accessibility-insights-ado-extension-release-production
          trigger:
              stages:
                  - package_publish_prod

extends:
    template: ado-extension-validation-template.yml
    parameters:
        taskUnderTest: accessibility-insights.prod.task.accessibility-insights@2
