# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

trigger: none

pr:
    branches:
        include:
            - main
    paths:
        include:
            - dev
            - pipelines/ado-extension-prod-validation.yaml
            - pipelines/ado-extension-validation-template.yaml

resources:
    pipelines:
        - pipeline: prod-release
          source: accessibility-insights-ado-extension-release-production
          trigger:
              stages:
                  - package_publish_prod

pool:
    vmImage: ubuntu-latest

extends:
    template: ado-extension-validation-template.yaml
    parameters:
        taskUnderTest: accessibility-insights.prod.task.accessibility-insights@2
