# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

trigger: none

pr: none

resources:
    pipelines:
        - pipeline: prod-release
          source: accessibility-insights-ado-extension-release-production
          trigger:
              stages:
                  - package_publish_staging

    repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool: 
      name: a11y-insights-pool-dev
      image: ubuntu-22.04-secure 
      os: linux 
         
    stages:
    - stage: Stage
      jobs:
      - template: ado-extension-validation-template.yaml
        parameters:
            taskUnderTest: accessibility-insights.staging.task.accessibility-insights@3
