# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

trigger: none

pr: none

resources:
    pipelines:
        - pipeline: prod-release
          source: accessibility-insights-ado-extension-release-production
          trigger:
              stages:
                  - package_publish_prod

pool: a11y-ado-auth

extends:
    template: ado-extension-validation-template.yaml
    parameters:
        taskUnderTest: accessibility-insights.prod.task.accessibility-insights@3
