# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

trigger: # trigger only affects CI builds
    branches:
        include:
            - main

variables:
    linuxImage: 'ubuntu-18.04'
    windowsImage: 'windows-2019'

jobs:
    - job: 'BuildAndCheckCodeStyling'
      pool:
          vmImage: $(linuxImage)
          demands: npm
      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: '16.x'
            displayName: use node 16.x

          - script: yarn install --frozen-lockfile
            displayName: Install dependencies

          - script: yarn copyright:check
            displayName: Check copyright headers

          - script: yarn format:check
            displayName: Check code formatting

          - script: yarn cbuild
            displayName: Build

          - script: yarn lint:check
            displayName: Check for lint errors

          - script: yarn test -- -- --ci --coverage
            displayName: Run tests
            env:
                NODE_OPTIONS: --max_old_space_size=4096

          - script: yarn publish-code-coverage -t $(CODECOV_TOKEN)
            displayName: Publish code coverage to codecov

    - job: 'SDT'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      pool:
          vmImage: $(windowsImage)
          demands: npm
      steps:
          - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
            displayName: 'Run CredScan'
            inputs:
                toolMajorVersion: V2
                debugMode: false

          - task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@1
            displayName: 'Run PoliCheck'
            inputs:
                targetType: F
                SOMEnabled: true

          - task: securedevelopmentteam.vss-secure-development-tools.build-task-report.SdtReport@1
            displayName: 'Generate CodeAnalysisLogs for TSA'
            inputs:
                CredScan: true
                PoliCheck: true

          - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@2
            displayName: 'Publish CodeAnalysisLogs Artifact for Scans tab UI'
            condition: succeededOrFailed()

          - task: securedevelopmentteam.vss-secure-development-tools.build-task-uploadtotsa.TSAUpload@1
            displayName: 'TSA Upload'
            inputs:
                tsaVersion: TsaV2
                codebase: NewOrUpdate
                codeBaseName: '$(TSACodebaseName)'
                notificationAlias: '$(notificationAlias)'
                codeBaseAdmins: '$(codeBaseAdmins)'
                instanceUrlForTsaV2: $(instanceUrlForTsaV2)
                projectNameMSENG: $(projectNameMSENG)
                areaPath: '$(areaPath)'
                iterationPath: '$(iterationPath)'
                uploadAPIScan: false
                uploadBinSkim: false
                uploadFortifySCA: false
                uploadFxCop: false
                uploadModernCop: false
                uploadPREfast: false
                uploadRoslyn: false
                uploadTSLint: false

          - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
            displayName: 'Break build on CredScan violations'
            inputs:
                CredScan: true

    - job: 'PublishBuildDrops'
      pool:
          vmImage: $(linuxImage)
          demands: npm
      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: '16.x'
            displayName: use node 16.x

          - script: yarn install --frozen-lockfile
            displayName: Install dependencies

          - script: yarn cbuild
            displayName: Build

          - task: ComponentGovernanceComponentDetection@0
            displayName: 'dependency detection (Component Governance)'
            inputs:
                ignoreDirectories: 'drop,dist,extension,node_modules'

          - task: msospo.ospo-extension.8d7f9abb-6896-461d-9e25-4f74ed65ddb2.notice@0
            displayName: 'generate NOTICE.html file'
            inputs:
                outputfile: '$(System.DefaultWorkingDirectory)/NOTICE.html'
                outputformat: html

          - task: CopyFiles@2
            displayName: 'Copy Files to: gh-drop'
            inputs:
                Contents: |
                    $(System.DefaultWorkingDirectory)/NOTICE.html
                    $(System.DefaultWorkingDirectory)/packages/gh-action/dist/index.js
                    $(System.DefaultWorkingDirectory)/packages/gh-action/dist/package.json
                    $(System.DefaultWorkingDirectory)/packages/gh-action/dist/yarn.lock
                    $(System.DefaultWorkingDirectory)/packages/gh-action/action.yml

                TargetFolder: '$(System.DefaultWorkingDirectory)/drop'

          - task: CopyFiles@2
            displayName: 'Copy Notices.html to: ado-drop'
            inputs:
                Contents: |
                    $(System.DefaultWorkingDirectory)/NOTICE.html

                TargetFolder: '$(System.DefaultWorkingDirectory)/packages/ado-extension/dist'

          - bash: |
                echo '<!--
                Copyright (c) Microsoft Corporation. All rights reserved.
                Licensed under the MIT License.
                -->
                              
                # About
                              
                This release was generated from this source tree [$(Build.SourceVersion)](https://github.com/microsoft/accessibility-insights-action/tree/$(Build.SourceVersion)).
                ' > '$(System.DefaultWorkingDirectory)/drop/RELEASE_COMMIT.md'

            displayName: 'Generate Release README Info'

          - task: CopyFiles@2
            displayName: 'Copy ReadMe to: ado-drop'
            inputs:
                Contents: |
                    $(System.DefaultWorkingDirectory)/drop/RELEASE_COMMIT.md

                TargetFolder: '$(System.DefaultWorkingDirectory)/packages/ado-extension/dist'

          - task: PublishBuildArtifacts@1
            inputs:
                pathtoPublish: '$(System.DefaultWorkingDirectory)/drop'
                artifactName: 'drop'
            displayName: publish drop

          - task: PublishBuildArtifacts@1
            inputs:
                pathtoPublish: '$(System.DefaultWorkingDirectory)/packages/ado-extension/dist'
                artifactName: 'ado-extension-drop'
            displayName: publish ado-extension-drop
