# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

trigger:
    - main

variables:
    linuxImage: 'ubuntu-18.04'
    windowsImage: 'windows-2019'

jobs:
    - job: 'BuildAndCheckCodeStyling'
      pool:
          vmImage: $(linuxImage)
          demands: npm
      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: '12.x'
            displayName: use node 12.x

          - script: yarn install --frozen-lockfile
            displayName: Install dependencies

          - script: yarn cbuild
            displayName: Build

          - task: accessibility-insights.test.task.accessibility-insights-test@9
            inputs:
                siteDir: $(System.DefaultWorkingDirectory)/dev/website-root
                repoServiceConnectionName: 'ADO test ortiga'
            displayName: 'Run accessibility testing'

          - task: PublishBuildArtifacts@1
            inputs:
                pathtoPublish: '$(System.DefaultWorkingDirectory)/_accessibility-reports'
                artifactName: Report
            displayName: publish accessibility reports
