# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
    - name: variableGroupName
      displayName: Deployment variable group. Should contain variables named extensionId, extensionName, publisherId, and (optionally) appInsightsConnectionString.
      type: string
      default: 'a11y-insights-ado-extension-canary'
    - name: versionOverride
      displayName: Override extension version (for non-patch version upgrades, specify version number)
      type: string
      default: 'ignore-for-patch-version-upgrade'

variables:
    - ${{ if ne(parameters.versionOverride, 'ignore-for-patch-version-upgrade') }}:
          - name: extensionVersionOverride
            value: ${{ parameters.versionOverride }}

trigger: none

pool:
    name: $(a11yInsightsPool)
    vmImage: $(linuxImage)
    demands:
        - ImageOverride -equals $(linuxImage)

resources:
    pipelines:
        - pipeline: accessibility-insights-action-ci
          source: accessibility-insights-action-ci
          trigger:
              branches: [main]

stages:
    - stage: package_publish_canary
      variables:
          - group: ${{ parameters.variableGroupName }}
      jobs:
          - template: release-template.yaml
            parameters:
                ${{ if eq(parameters.variableGroupName, 'a11y-insights-ado-extension-canary') }}:
                    environment: a11y-insghts-ado-extension-canary
                    shouldSign: true
                    visibility: preview
                ${{ if ne(parameters.variableGroupName, 'a11y-insights-ado-extension-canary') }}:
                    environment: a11y-insghts-ado-extension-test
                    shouldSign: false
                    visibility: private
