# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
    - name: variableGroupName
      displayName: Deployment variable group. Should contain variables named extensionId, extensionName, publisherId, and (optionally) appInsightsConnectionString.
      type: string
      default: 'a11y-insights-ado-extension-canary'
    - name: versionOverride
      displayName: Override extension version (for non-patch version upgrades, specify version number)
      type: string
      default: 'ignore-for-patch-version-upgrade'

variables:
    - ${{ if ne(parameters.versionOverride, 'ignore-for-patch-version-upgrade') }}:
          - name: extensionVersionOverride
            value: ${{ parameters.versionOverride }}

trigger: none

resources:
    repositories:
        - repository: 1esPipelines
          type: git
          name: 1ESPipelineTemplates/1ESPipelineTemplates
          ref: refs/tags/release
    pipelines:
        - pipeline: accessibility-insights-action-ci
          source: accessibility-insights-action-ci
          trigger:
              branches: [main]

extends:
    # Do not edit. This is the 1ES template that holds different SDL and compliance tasks that the template injects into the pipeline.
    # It uses the Official template because it's a production pipeline.
    template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines

    parameters:
        # Accessibility Insights team's 1ES hosted pool.
        # This variable is saved in Azure DevOps from the "Edit" pipeline view.
        pool:
            name: $(a11yInsightsPool)
            image: $(linuxImage)
            os: linux
            demands:
                - ImageOverride -equals $(linuxImage)

        sdl:
            sourceAnalysisPool:
                name: a11y-ado-auth
                image: windows-2022-secure
                os: windows

        stages:
            - stage: package_publish_canary
              variables:
                  - group: ${{ parameters.variableGroupName }}
              jobs:
                  - template: pipelines/release-template.yaml@self
                    parameters:
                        ${{ if eq(parameters.variableGroupName, 'a11y-insights-ado-extension-canary') }}:
                            environment: a11y-insghts-ado-extension-canary
                            shouldSign: true
                            visibility: preview
                            isProduction: false
                        ${{ if ne(parameters.variableGroupName, 'a11y-insights-ado-extension-canary') }}:
                            environment: a11y-insghts-ado-extension-test
                            shouldSign: false
                            visibility: private
                            isProduction: false
