# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
    - name: variableGroupName
      displayName: Deployment Variable Group
      type: string
      default: 'ado-extension-canary'
    - name: versionOverride
      displayName: version to deploy (only for test extensions)
      type: string
      default: 'ignore-if-canary'

variables:
    - ${{ if ne(parameters.variableGroupName, 'ado-extension-canary') }}:
          - name: extensionVersionOverride
            value: ${{ parameters.versionOverride }}

trigger: none

pool:
    vmImage: ubuntu-latest

resources:
    pipelines:
        - pipeline: accessibility-insights-action-ci
          source: accessibility-insights-action-ci
          trigger:
              branches: [main]

stages:
    - stage: package_publish_canary
      variables:
          - group: ${{ parameters.variableGroupName }}
      jobs:
          - template: release-template.yaml
            parameters:
                ${{ if eq(parameters.variableGroupName, 'ado-extension-canary') }}:
                    environment: ado-extension-canary
                    shouldSign: false
                    visibility: private
                ${{ if ne(parameters.variableGroupName, 'ado-extension-canary') }}:
                    environment: ado-extension-test
                    shouldSign: false
                    visibility: private
