# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
    - name: prodVersionOverride
      displayName: Production version to deploy
      type: string
      default: ''
    - name: stagingVersionOverride
      displayName: Override staging version
      type: string
      default: 'increment'

trigger: none

# Accessibility Insights team's 1ES hosted pool.
# This variable is saved in Azure DevOps from the "Edit" pipeline view.
pool:
    name: $(a11yInsightsPool)
    image: ubuntu-22.04-secure
    os: linux

resources:
    pipelines:
        - pipeline: accessibility-insights-action-ci
          source: accessibility-insights-action-ci

stages:
    - stage: package_publish_staging
      variables:
          - group: a11y-insights-ado-extension-staging
          - ${{ if ne(parameters.stagingVersionOverride, 'increment') }}:
                - name: extensionVersionOverride
                  value: ${{ parameters.stagingVersionOverride }}
      jobs:
          - template: release-template.yaml
            parameters:
                environment: a11y-insights-ado-extension-staging
                shouldSign: true
                visibility: preview

    - stage: create_release_tag
      variables:
          - name: tag
            value: v${{ parameters.prodVersionOverride }}-sources-ado
      jobs:
          - job: 'CreateReleaseTag'
            steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                      source: 'specific'
                      runVersion: 'specific'
                      project: $(resources.pipeline.accessibility-insights-action-ci.projectID)
                      pipeline: $(resources.pipeline.accessibility-insights-action-ci.pipelineID)
                      runId: $(resources.pipeline.accessibility-insights-action-ci.runID)
                      artifact: ado-extension-drop
                      path: '$(System.DefaultWorkingDirectory)/ado-extension-drop'

                - task: GitHubRelease@1
                  displayName: 'GitHub release'
                  inputs:
                      tag: '$(tag)'
                      action: edit
                      tagSource: userSpecifiedTag
                      gitHubConnection: 'a11y-insights-ada-cat-github-oauth'
                      isPreRelease: true
                      isDraft: true
                      target: $(resources.pipeline.accessibility-insights-action-ci.sourceCommit)
                      assets: '$(System.DefaultWorkingDirectory)/ado-extension-drop/NOTICE.html'

    - stage: package_publish_prod
      variables:
          - group: a11y-insights-ado-extension-prod
          - name: extensionVersionOverride
            value: ${{ parameters.prodVersionOverride }}
      jobs:
          - template: release-template.yaml
            parameters:
                environment: a11y-insights-ado-extension-prod
                shouldSign: true
                visibility: preview
