# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
    - name: prodVersionOverride
      displayName: Production version to deploy
      type: string
      default: ''
    - name: stagingVersionOverride
      displayName: Override staging version
      type: string
      default: 'increment'

trigger: none

pool:
    vmImage: ubuntu-latest

resources:
    pipelines:
        - pipeline: accessibility-insights-action-ci
          source: accessibility-insights-action-ci

stages:
    - stage: package_publish_staging
      variables:
          - group: ado-extension-staging
      ${{ if ne(${{ parameters.stagingVersionOverride }}, 'increment') }}:
          - name: extensionVersionOverride
            value: ${{ parameters.stagingVersionOverride }}
      jobs:
          - template: release-template.yaml
            parameters:
                environment: ado-extension-staging

    - stage: package_publish_prod
      variables:
          - group: ado-extension-prod
          - name: extensionVersionOverride
            value: ${{ parameters.prodVersionOverride }}
          - name: tag
            value: v${{ parameters.prodVersionOverride }}-sources-ado
      jobs:
          - template: release-template.yaml
            parameters:
                environment: ado-extension-prod

          - job: 'CreateReleaseTag'
            steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                      source: 'specific'
                      runVersion: 'specific'
                      project: $(resources.pipeline.accessibility-insights-action-ci.projectID)
                      pipeline: $(resources.pipeline.accessibility-insights-action-ci.pipelineID)
                      runId: $(resources.pipeline.accessibility-insights-action-ci.runID)
                      artifact: ado-extension-drop
                      path: '$(System.DefaultWorkingDirectory)/ado-extension-drop'

                - task: GitHubRelease@1
                  displayName: 'GitHub release'
                  inputs:
                      tag: '$(tag)'
                      action: edit
                      tagSource: userSpecifiedTag
                      gitHubConnection: 'ada-cat-github-repo-access'
                      isPreRelease: true
                      target: $(resources.pipeline.accessibility-insights-action-ci.sourceCommit)
                      assets: '$(System.DefaultWorkingDirectory)/ado-extension-drop/NOTICE.html'
