# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
    - name: environment
      displayName: deployment environment
      type: string
    - name: shouldSign
      displayName: whether to sign VSIX file
      type: string
      default: 'true'
    - name: visibility
      displayName: marketplace visibility
      type: string
    - name: isProduction
      displayName: whether to deploy to production
      type: string

jobs:
    - job: package_job
      pool:
          name: $(a11yInsightsPool)
          vmImage: $(linuxImage)
          demands:
              - ImageOverride -equals $(linuxImage)
      templateContext:
          inputs:
              - input: pipelineArtifact
                source: 'specific'
                runVersion: 'specific'
                project: $(resources.pipeline.accessibility-insights-action-ci.projectID)
                definition: $(resources.pipeline.accessibility-insights-action-ci.pipelineID)
                runId: $(resources.pipeline.accessibility-insights-action-ci.runID)
                artifactName: ado-extension-drop
                targetPath: '$(System.DefaultWorkingDirectory)/ado-extension-drop'
          outputs:
              - output: pipelineArtifact
                targetPath: '$(Build.ArtifactStagingDirectory)'
                artifactName: '${{ parameters.environment }}-vsix'
                publishLocation: 'Container'
      steps:
          - template: package-vsix-file.yaml@self
            parameters:
                environment: ${{ parameters.environment }}
                shouldSign: ${{ parameters.shouldSign }}
                visibility: ${{parameters.visibility}}

    - deployment: publish_vsix_file
      displayName: deploy vsix file
      dependsOn: package_job
      templateContext:
          type: releaseJob
          isProduction: ${{ parameters.isProduction }}
          inputs:
              - input: pipelineArtifact
                buildType: 'current'
                downloadType: 'single'
                artifactName: '${{ parameters.environment }}-vsix'
                targetPath: '$(System.DefaultWorkingDirectory)/${{ parameters.environment }}-vsix'
      environment: ${{ parameters.environment }}
      strategy:
          runOnce:
              deploy:
                  steps:
                      - template: publish-vsix-file.yaml@self
                        parameters:
                            environment: ${{ parameters.environment }}
                            visibility: ${{parameters.visibility}}
