# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
    - name: environment
      displayName: deployment environment
      type: string
    - name: shouldSign
      displayName: whether to sign VSIX file
      type: string
    - name: visibility
      displayName: marketplace visibility
      type: string

jobs:
    - job: package_job
      pool:
          name: $(a11yInsightsPool)
          vmImage: $(linuxImage)
          demands:
              - ImageOverride -equals $(linuxImage)
      steps:
          - template: package-vsix-file.yaml
            parameters:
                environment: ${{ parameters.environment }}
                shouldSign: ${{ parameters.shouldSign }}
                visibility: ${{parameters.visibility}}
    - deployment: publish_vsix_file
      displayName: deploy vsix file
      dependsOn: package_job
      environment: ${{ parameters.environment }}
      strategy:
          runOnce:
              deploy:
                  steps:
                      - template: publish-vsix-file.yaml
                        parameters:
                            environment: ${{ parameters.environment }}
                            visibility: ${{parameters.visibility}}
