# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: Release Action

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Enter the tag'
        required: true
      commit_sha:
        description: 'Enter the SHA commit you'd like to release'
        required: false

  jobs:
    Release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2

        - name: Setup node
          uses: actions/setup-node@v1
          with:
            node-version: 12.x

        - name: Install dependencies
          run: yarn install --frozen-lockfile

        - name: Build
          run: yarn cbuild

        - name: Run the release script
          run: ./release.ps1 ${{ github.event.inputs.release_tag }} ${{ github.event.inputs.commit_sha }}
