# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: Release

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Enter the tag'
        required: true
        default: ''
      commit-sha:
        description: 'Enter the commit sha'
        required: false
        default: ''
      
      
  jobs:
    release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2

        - name: Setup node
          uses: actions/setup-node@v1
          with:
            node-version: 12.x

        - name: Install dependencies
          run: yarn install --frozen-lockfile

        - name: Build
          run: yarn cbuild

        - name: Run the release script
          run: ./release.ps1 ${{ github.event.inputs.release-tag }} ${{ github.event.inputs.commit-sha }}
