# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: Release

on:
  workflow_dispatch:
    paths-ignore:
      - '.github/workflows/nodejs.yml'
    inputs:
      release-tag:
        description: 'Enter the tag'
        required: true
      commit-sha:
        description: 'Enter the commit sha'
        required: true     
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.access_token }}

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn cbuild

      - name: Run the release script
        run: sh ./release.sh ${{ github.event.inputs.release-tag }} ${{ github.event.inputs.commit-sha }}
